version: 2.1
workflows:
  build_test_push:
    jobs:
      - test
      - build-and-push-image:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy-infrastructure:
          type: approval
          requires:
            - build-and-push-image
          filters:
            branches:
              only:
                - master

jobs:
  test:
    docker:
      - image: cimg/node:16.2
    working_directory: ~/personal-website-repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - run: yarn test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/personal-website-repo
          paths: .
  build-and-push-image:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Configure AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region.default $AWS_DEFAULT_REGION
      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL
      - run:
          name: Build and push image to AWS ECR
          command: |
            docker build -t $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPO_NAME:$CIRCLE_SHA1 -t $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPO_NAME:latest .
            docker push $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPO_NAME:$CIRCLE_SHA1
            docker push $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPO_NAME:latest
  deploy-infrastructure:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - run:
          name: Configure AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region.default $AWS_DEFAULT_REGION
      - run:
          name: Build infra
          command: |
            cd ecs-infrastructure
            export TF_VAR_app_environment="prod"
            export TF_VAR_aws_ecr_image_url="$AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPO_NAME"
            terraform init
