version: 2.1
workflows:
  build_test_push:
    jobs:
      - test
      - build-and-push-image:
          requires:
            - test
jobs:
  test:
    docker:
      - image: cimg/node:16.2
    working_directory: ~/personal-website-repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - run: yarn test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/personal-website-repo
          paths: .
  build-and-push-image:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - run: unzip awscliv2.zip
      - run: sudo ./aws/install
      - run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - run: aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - run: aws configure set region.default $AWS_DEFAULT_REGION
      - run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL
      - run: sudo service docker status
      - run: sudo systemctl start docker
      - run: docker build -t $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPO_NAME:$CIRCLE_SHA1 -t $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPO_NAME:latest .
      - run: docker push $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPO_NAME:$CIRCLE_SHA1
      - run: docker push $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPO_NAME:latest

