version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
workflows:
  build_test_push:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          repo: ${AWS_ECR_REPO_NAME}
          tag: 'latest, ${CIRCLE_BUILD_NUM}'
          requires:
            - test
jobs:
  test:
    docker:
      - image: cimg/node:16.2
    working_directory: ~/personal-website-repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - run: yarn test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/personal-website-repo
          paths: .
  push-image:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - run: unzip awscliv2.zip
      - run: sudo ./aws/install
      - run: aws configure
      - run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL
